# Generated by Django 4.0.1 on 2022-05-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_orders_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
